### ISSUE TITLE
Deprecate the --partial options

### ISSUE THREAD

**Issue by mtreinish** [mtreinish/stestr#108]
Tracing through the code the use of --partial on _stestr run_ and _stestr load_ don't seem to have any real effect. This option was directly ported from testr in the initial fork and I didn't really think about it but the flags serve no real purpose from what I can tell. I think the original idea was to distinguish an entry in a repository for a full run vs one that was a subset. (but you'd have to check with the testrepository authors on that) But nothing else respects or expects that difference, and from an end user perspective it doesn't really matter. The repository contains the historical record of previous runs and information for scheduling is aggregated independently from that. So it doesn't really matter if the record is for a partial execution or not.

Therefore I think it'll be good to just remove those options, Unfortunately the options are in our stable interfaces (both the cli and python commands api) so we'll have to deprecate them for a bit first. We can remove the flags and just print a deprecation warning on usage to warn people things are going away.

The only functional code that seems to use it is in the repository:

https://github.com/mtreinish/stestr/blob/86b8ee4709538e18b72a7373ce9dad19c5015a12/stestr/repository/file.py#L314-L322

and 

https://github.com/mtreinish/stestr/blob/82b3efc3f4d872d04424b8cdfd466942dbf95d92/stestr/repository/memory.py#L163-L164

Which are related, the file repo uses the memory repo call after that highlighted if statement. I'm not exactly sure on the function of that code so investigation will be needed to understand what's being triggered there and how to implement it without a user facing flag.

**Comment by masayukig** [comment]
oh, github doesn't support the "Partial-Bug" keyword :-p

**Comment by mtreinish** [comment]
heh, I don't think github supports any keywords except for the '#' references. I haven't found any automation around closing issues. Although I haven't bothered to read any of the documentation on it.

**Comment by mtreinish** [comment]
@masayukig do you think we can close this since we landed the deprecation patch? Or do you think we should wait until the removal patch at some point in the future (it'll probably be a long time because it's an annoying breaking change)

**Comment by masayukig** [comment]
Yeah, I prefer closing this issue and make a new issue for removing the --partial option. And it's better to change the title of this issue to like "Deprecate the --partial options".
