### ISSUE TITLE
Add a silent output mode to stestr run and stestr load

### ISSUE THREAD

**Issue by mtreinish** [mtreinish/stestr#121]
There is an occasional use case for having a flag on stestr run and load that doesn't output anything. It just returns either 0 or 1. We should add a flag to stestr run and load that does this.

The primary motivator for this is the --analyze-isolation flag which does multiple test runs during it's operation. If there are failures they print to stdout making it confusing to follow.

**Comment by masayukig** [comment]
Is the '-q'/'--quiet' option for this mode? It seems that it doesn't work now, though.

```
  -q, --quiet           Turn off output other than the primary output for a
                        command and any errors.
```

**Comment by mtreinish** [comment]
Yeah, I don't think I ever did anything with that besides the definition. IIRC it''s defined in the base cli module, we probably can reuse the definition if we want, but it's more the implementation details that matter for this bug.

**Comment by masayukig** [comment]
How about like this? #124

**Comment by mtreinish** [comment]
#124 landed so we can close this
