### ISSUE TITLE
"WARNING: missing Worker N! Race in testr accounting." when using stestr --failing

### ISSUE THREAD

**Issue by cdent** [mtreinish/stestr#137]
While iteratively using the `--failing` argument to find and fix problems in a large suite of tests (the OpenStack nova unit tests) I received 

```
WARNING: missing Worker 9! Race in testr accounting.
```

warnings for one or more workers, when spreading tests across 16 cores. As the number of tests being run shrank, the chance for the warning seemed to increase.

It seemed to be the case that a worker was reporting the problem when rationalizing the discovered tests against the list of failing tests and resulting in none.

**Comment by mtreinish** [comment]
Related, but not at all relevant to fixing this bug. I just pushed up https://github.com/mtreinish/stestr/pull/138 to remove the second half of the error message. Just putting that here for the record so in case people hit this after that patch lands to indicate the second half of the message will go away.
