### ISSUE TITLE
Windows CI failing on pip >=10.0.0

### ISSUE THREAD

**Issue by mtreinish** [mtreinish/stestr#165]
The windows CI is failing on installing tox with pip releases >=10.0.0. The failure is:

For example from: https://ci.appveyor.com/project/mtreinish/stestr/build/1.0.482/job/vcjjyshnpcupdyi2

```
pip install -U tox
Traceback (most recent call last):
  File "c:\python27-x64\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27-x64\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27-x64\Scripts\pip.exe\__main__.py", line 5, in <module>
ImportError: cannot import name main
```

This looks like it could be related to the upstream pip issue: https://github.com/pypa/pip/issues/5223 but that is supposed to be fixed in pip 10.0.1. But this failure is still occurring in our CI environment.

**Comment by masayukig** [comment]
hmm, I actually have no idea for this so far. I'll make an test environment locally to reproduce this when I have the time..

**Comment by masayukig** [comment]
well, I couldn't reproduce this issue in my local windows environment. The unit test with `tox -e py27 -r` was successful. The python version is a bit different from Appveyor, actually. But I don't think it's the only one difference.
```
C:\Users\masay\git\stestr>pip --version
pip 10.0.1 from c:\python27\lib\site-packages\pip (python 2.7)

C:\Users\masay\git\stestr>python --version
Python 2.7.15
```

**Comment by mtreinish** [comment]
This was fixed by a combination of image updates and some downstream lib fixes. I have the cap removal proposed in #176. There was one small change needed, now to upgrade pip you have to call python -m pip instead of the console script directly.
