### ISSUE TITLE
[RFE] pytest-style filesystem paths

### ISSUE THREAD

**Issue by stephenfin** [mtreinish/stestr#180]
The pytest runner allows you to provide a filepath-like arguments to run tests instead of paths runners.

    pytest test_mod.py::TestClass::test_method

We already have support for the path aspect of this, using the `--no-discover`/`-n` option but this does not allow you specify a class/method.

    stestr -n test_mod.py

To do this, you need to use a Python path.

    stestr test_mod.TestClass.test_method

It would be helpful to support the pytest-style case as this is frequently quicker to run and doesn't require discovery outside of the file provided (or so I assume).

**Comment by mtreinish** [comment]
Yep, this would be a good enhancement, and pretty straightforward to improve. The code handling this right just does a straight '/' to '.' replacement and passes the path to the underlying test runner:

https://github.com/mtreinish/stestr/blob/master/stestr/commands/run.py#L315-L317

We just need to modify this to handle converting the pytest like path to something that subunit.run understands.
