### ISSUE TITLE
No wheel in PyPi

### ISSUE THREAD

**Issue by darkvertex** [mtreinish/stestr#201]
### Issue description

https://pypi.org/project/stestr/#files has no .whl files.

It'd be nice to have some as it speeds up pip installing.

#### Expected behavior and actual behavior

Expected pip to find a .whl file.

#### Steps to reproduce the problem

`pip install -v stestr`

### System information

**stestr version (`stestr --version`):**

2.1.1

**Python release (`python --version`):**

2.7.13

**Comment by mtreinish** [comment]
That's a good point, I'll work on building and uploading a wheel soon (hopefully today or tomorrow) and I'll add that to my release process script to make sure we do it in the future.

**Comment by mtreinish** [comment]
Sorry that took so long, I got swamped with some other things and this fell through the cracks. I've uploaded wheels for 2.1.1: https://pypi.org/project/stestr/#files I'm planning to release a new bug fix release soon 2.1.2 and will have building and uploading wheels as part of the release process for that too.
