### ISSUE TITLE
test_listing_fixture is a bad name

### ISSUE THREAD

**Issue by mtreinish** [mtreinish/stestr#21]
The name for the module stestr.test_listing_fixture and it's class name TestListingFixture are a terrible name and misleading in their function. It sounds like it runs tests on the listing_fixture. The problem is I'm not exactly sure how to describe it.

Currently the class TestListingFixture defines a [fixture](https://pypi.python.org/pypi/fixtures) for the lifecycle of a temp file that contains a list of test_ids. These test_ids are either provided as an input parameter or found through running test discovery (by launching subunit.run discover --list). The fixture also provides functions that require the existence of that temporary test list, which includes the launching of the test runner workers. This means that the test_listing_fixture is where we actually run the test processes. (which is the source of the confusion around the name)

If anyone has an idea for a better name feel free to push a patch renaming things, or just comment on the bug.

**Comment by shriya999** [comment]
how about test_processor_fixture as the main action is processing a test according to a list of test ids?

**Comment by mtreinish** [comment]
Hmm, I like that direction. Maybe we make the module name test_processor.py and the class TestProcessorFixture. I think that will work well. Would you like to submit a pull request making that switch? If not I can do it, but since you came up with the name you should get the commit in the log. :)

**Comment by shriya999** [comment]
Yes i would like to make a pull request as this will be my first bug!! Thanks for reviewing it so fast 🗡

**Comment by mtreinish** [comment]
Sorry, I missed your comments here. I believe github has a method for creating git commits via their web UI. Although, I've never personally used it, because the normal git workflow is much faster IMHO. So you create a pull request you will need to have git on your local machine and create a git commit

Unfortunately I don't really think waiting until May is an option.

**Comment by mtreinish** [comment]
Sorry, I missed your comments here. I believe github has a method for creating git commits via their web UI. Although, I've never personally used it, because the normal git workflow is much faster IMHO. So you create a pull request you will need to have git on your local machine and create a git branch with a commit with the renamed files (and import statements that were using the old name). Once that's done you push the branch up to your github fork and create a pull request from the fork.

Here are some docs I found on how to do this:

https://guides.github.com/introduction/flow/

https://help.github.com/articles/about-pull-requests/

http://rogerdudler.github.io/git-guide/

This one includes links about doing everything in github's web UI:

https://help.github.com/articles/github-flow/

Unfortunately I don't really think waiting until May is an option. I want to include this change in the next release so we can start to stabilize the Python API; which this is the first step towards.

**Comment by mtreinish** [comment]
If you need some more help getting started with git and/or github, feel free to send me an email (my email address is on my github user page) and we can work through things in more depth there.

**Comment by mtreinish** [comment]
@shriya999 Do you still want to try and tackle fixing this?

**Comment by shriya999** [comment]
Hello,

Yes i would love to tackle the problem . I will try it out  and let you
know by 26th May at the latest.

Thanks for waiting :)

**Comment by shriya999** [comment]
Hi again,

I have created the pull request using their web UI. However i did try doing
it using the normal git workflow and so i created a local repository but i
am not able to add to the index using the command git add
test_listing_fixture.py . Or else when i tried using the remote server
method i didnt understand what the host name would be. Please help me out
here :)

Thanks.

**Comment by mtreinish** [comment]
The normal git workflow is documented here: https://yangsu.github.io/pull-request-tutorial/ pretty well. The thing missing from that guide is after your create your new branch is you commit your changes to the local repo before pushing back to github.

The normal workflow for me is:

1. git clone $(ssh url from github fork) (you might need to update/recreate your fork if it's out of date)
2. cd stestr
3. git checkout -b feature-name
4. make local changes (in this case updating the module name and class name along with all references)
5. git commit -a (Write a descriptive commit message see: https://github.com/erlang/otp/wiki/Writing-good-commit-messages and https://chris.beams.io/posts/git-commit/)
6. git push
7. Go to github for your local fork and create a pull request form the branch (it should show it in the ui)

**Comment by mtreinish** [comment]
#65 has merged, this issue is not closed
