### ISSUE TITLE
The python executable used by stestr does not consider the interpreter used by stestr itself

### ISSUE THREAD

**Issue by ghost** [mtreinish/stestr#215]
When stestr executes additional python code, it sets the python interpreter as follow:

`python = 'python' if sys.platform == 'win32' else '${PYTHON:-python}'`

But this leads to a failure, for example, when
- stestr is executed through python3
- the alias for `python` is `python2` (as in most *nix systems nowadays)
- python2 is not available, or available but without many libraries installed (namely not subunit)
- PYTHON is not defined

then stestr execution fails with:

```
/usr/bin/python: No module named subunit        
                       
=========================                                    
Failures during discovery    
=========================
```

It would make more sense to invoke additional commands using the same interpreter used by stestr itself by default. Users should still be able to override the value by setting PYTHON as it happens nowadays.

**Comment by aspiers** [comment]
I just wasted a bunch of time trying to figure out why this was happening:

```
$ .tox/py27/bin/stestr run nova.tests.unit.virt.libvirt.test_fakelibvirt                                                                                      
/usr/bin/python: No module named subunit                                                                                                                         
                                                                                                                                                                 
=========================
Failures during discovery
=========================

================================================================================
The above traceback was encountered during test discovery which imports all the found test modules in the specified test_path.
```

whereas it didn't happen via `tox -e py27`.  Finally I figured out that I needed either

    .tox/py27/bin:$PATH stestr run -n nova.tests.unit.virt.libvirt.test_fakelibvirt

or:

    tox -e py27 -- -n nova.tests.unit.virt.libvirt.test_fakelibvirt

It would be great if a new release could be made soon, to avoid others falling into the same trap.  Thanks!

**Comment by aspiers** [comment]
... especially considering that for some reason, a google of `stestr "No module named subunit"` fails to find this issue :angry:
