### ISSUE TITLE
Clear link to GitHub repo missing from PyPI and RTD

### ISSUE THREAD

**Issue by aspiers** [mtreinish/stestr#218]
I wanted to report some issues I just discovered with `stestr` so I needed to locate where to report them.  I was very surprised to find:

- It appeared nowhere in the first 3 pages of Google search results for `stestr`

- It appeared nowhere in the display of package metadata at https://pypi.org/project/stestr/ (when looking more closely later, I noticed that the GitHub clone URL was included in the installation instructions, but IMHO this is not obvious enough

- The only hyperlink under "Project links" on https://pypi.org/project/stestr/ is "Homepage" which links to the docs, and there is not a single mention of the GitHub repository within the doc contents.  Luckily there was a hint in the "Edit on GitHub" link in the top-right corner, so I eventually found it.

Once I had found the GitHub repo, I also found `CONTRIBUTING.md`, but by then it was telling me what I already knew.

So if you want more contributors, I strongly recommend making it easier to find the GitHub repo.

**Comment by mtreinish** [comment]
The homepage for pypi was added in: https://github.com/mtreinish/stestr/pull/90 I don't really care what the link is since I never really use it. I'm fine with this being the link to github repo if you think that's better, feel free to push PR changing this I'll approve it.

I do find it surprising that github doesn't show up in the first 3 pages of google results, but that's not something we can actually control.

**Comment by aspiers** [comment]
[**@mtreinish**](https://github.com/mtreinish) commented on [January 29, 2019 5:46 PM](https://github.com/mtreinish/stestr/issues/218#issuecomment-458637535 "2019-01-29T17:46:28Z - Replied by Github Reply Comments"):
> The homepage for pypi was added in: [#90](https://github.com/mtreinish/stestr/pull/90) I don't really care what the link is since I never really use it. I'm fine with this being the link to github repo if you think that's better, feel free to push PR changing this I'll approve it.

No, I wasn't thinking specifically of changing that link but rather ensuring that *all* the main links are visible, including that one.  setuptools conveniently provides `project_urls` for this:

- https://packaging.python.org/guides/distributing-packages-using-setuptools/#project-urls
- https://setuptools.readthedocs.io/en/latest/setuptools.html#metadata

and even `download_url`, in fact.  Additionally it would be worth taking a leaf out of cliff's book and including a "For Contributors" section in the docs:

- https://docs.openstack.org/cliff/latest/contributors/index.html

> I do find it surprising that github doesn't show up in the first 3 pages of google results, but that's not something we can actually control.

Actually I suspect you can :-) although obviously not directly or fully.  As I'm sure you know there is a whole dark art around this called SEO.  However in this simple case, I suspect there is no need to try anything fancy; most likely it will be good enough to add a few cross-links in key places - probably just the ones I've suggested above in fact.  When both PyPI and readthedocs.io are pointing to the GitHub page, it will naturally rise in the rankings.

**Comment by mtreinish** [comment]
I'd like to have this done before we push the 2.3.0 release (this is the last thing I think before we can do that). @masayukig and/or @aspiers if you get a chance could one of you throw up a PR making these changes to the metadata and the docs? Otherwise I'll probably get to it next week at some point.

**Comment by masayukig** [comment]
@mtreinish , @aspiers how about like #227 ?
