### ISSUE TITLE
stestr needs a fail fast option

### ISSUE THREAD

**Issue by ssbarnea** [mtreinish/stestr#230]
### Issue description

stestr needs a fast fail feature where it will stop execution on first failure. If user can even trigger this via an evironment variable or a global. (outside code repository) option even better. Having a CLI argument may help but is not covenient because it would require extra steps like `tox -e py27 -- --fast-fail` and sometimes even having to edit the tox.ini file to alter behaviour. 

The idea of having an outside code-base way to control what stestr does when it encounters an error is to ease developer work.

Too often I came to cases where the stability of the system was jeopardised because stestr started using all available cpu cores with tests that were failing due to system configuration issue.

This issue is not related to a specific project, I seen this in lots of projects where running tox with stestr caused a less optimal results.

PS. This also means that it would be really useful to have an environment variable that enables --serial. Following the pattern used by other tools, having a STESTR_SERIAL could be useful too.

**Comment by masayukig** [comment]
> PS. This also means that it would be really useful to have an environment variable that enables --serial. Following the pattern used by other tools, having a STESTR_SERIAL could be useful too.

FWIW, are user config files helpful for this case?
 https://stestr.readthedocs.io/en/latest/MANUAL.html#user-config-files

**Comment by ssbarnea** [comment]
Sure! Sorry for not finding the original issue which is really weird especially due to the suggestion feature in github. Maybe that feature was not enabled in the repository? (it can save a lot of duplicates).
