### ISSUE TITLE
Python 2.7 EoL Planning 

### ISSUE THREAD

**Issue by mtreinish** [mtreinish/stestr#237]
With the pending end of life for python 2.7 on January 1st 2020 we need to have a plan for dropping stestr support for python 2.7. Likely at some point in January 2020. Clearly this will warrant a stestr 3.0 release, but we should have the plan written down in the docs or on github somewhere. We also should remove all the six and python 2 compat code from the repo prior to the 3.0 release.

**Comment by mtreinish** [comment]
Thinking about this some more today, we probably should also create a `remove-python2-support` branch where we can stage all the changes needed for this. Then when it's time for the 3.0.0 release we can merge that into master.

**Comment by masayukig** [comment]
yeah, that makes sense.

**Comment by masayukig** [comment]
I just made and pushed the branch as a first step. https://github.com/mtreinish/stestr/tree/remove-python2-support

**Comment by masayukig** [comment]
TODO
- [ ] Set a target date (Likely, some point in January 2020)
- [ ] Create `remove-python2-support` branch
- [ ] Write document for the EoL
- [ ] Remove all six and python 2 compatible code

**Comment by mtreinish** [comment]
@masayukig while #287 closes this from a functional point of view I'm wondering if we need additional documentation updates prior to releasing 3.0.0. Do you have any thoughts?

**Comment by masayukig** [comment]
@mtreinish I think the README.rst note is enough but it might be good to modify some for the 3.0.0 release like this?

```
.. note:: stestr v2.x.x release series are the last series that supports
    Python 2. Support for Python 2.7 was dropped in stestr release 3.0.0.
```

**Comment by mtreinish** [comment]
@masayukig see #290 hopefully that looks good. Once you merge that I'll go ahead and push out the 3.0.0 release.
