### ISSUE TITLE
stestr attachment lines are escaped on Python 3

### ISSUE THREAD

**Issue by aspiers** [mtreinish/stestr#243]
### Issue description

When tests fail, lines of attachments are sometimes escaped as byte strings.

### Observed output

```
Captured stderr:
~~~~~~~~~~~~~~~~
    b'/home/zuul/src/opendev.org/openstack/neutron/.tox/py36/lib/python3.6/site-packages/webob/acceptparse.py:1167: DeprecationWarning: The MIMEAccept class has been replaced by webob.acceptparse.create_accept_header. This compatibility shim will be deprecated in a future version of WebOb.'
    b'  DeprecationWarning'
    b'/home/zuul/src/opendev.org/openstack/neutron/.tox/py36/lib/python3.6/site-packages/webob/acceptparse.py:1051: DeprecationWarning: The behavior of AcceptValidHeader.best_match is currently being maintained for backward compatibility, but it will be deprecated in the future, as it does not conform to the RFC.'
    b'  DeprecationWarning,'
    b''
```

### Expected output

```
Captured stderr:
~~~~~~~~~~~~~~~~
    /home/zuul/src/opendev.org/openstack/neutron/.tox/py36/lib/python3.6/site-packages/webob/acceptparse.py:1167: DeprecationWarning: The MIMEAccept class has been replaced by webob.acceptparse.create_accept_header. This compatibility shim will be deprecated in a future version of WebOb.
      DeprecationWarning
    /home/zuul/src/opendev.org/openstack/neutron/.tox/py36/lib/python3.6/site-packages/webob/acceptparse.py:1051: DeprecationWarning: The behavior of AcceptValidHeader.best_match is currently being maintained for backward compatibility, but it will be deprecated in the future, as it does not conform to the RFC.
      DeprecationWarning,
    
```

### Additional information

This significantly impacts legibility when stuff gets escaped, e.g.

    b'2019-05-29 21:52:30,156 ERROR [nova.scheduler.client.report] [req-2206d054-b058-4f34-ac16-f6d4d04aab3f] Failed to update inventory to [{\'VCPU\': {\'total\': 2, \'min_unit\': 1, \'max_unit\': 2, \'step_size\': 1, \'allocation_ratio\': 16.0, \'reserved\': 0}, \'MEMORY_MB\': {\'total\': 4096, \'min_unit\': 1, \'max_unit\': 4096, \'step_size\': 1, \'allocation_ratio\': 1.5, \'reserved\': 512}, \'MEM_ENCRYPTION_CONTEXT\': {\'total\': 0, \'min_unit\': 0, \'max_unit\': 0, \'step_size\': 1, \'allocation_ratio\': 1.0, \'reserved\': 0}, \'DISK_GB\': {\'total\': 1, \'min_unit\': 1, \'max_unit\': 1, \'step_size\': 1, \'allocation_ratio\': 1.0, \'reserved\': 0}}] for resource provider with UUID 31e796ab-0940-4067-817d-b640c5689407.  Got 400: {"errors": [{"status": 400, "title": "Bad Request", "detail": "The server could not comply with the request since it is either malformed or otherwise incorrect.\\n\\n JSON does not validate: 0 is less than the minimum of 1  Failed validating \'minimum\' in schema[\'properties\'][\'inventories\'][\'patternProperties\'][\'^[A-Z0-9_]+$\'][\'properties\'][\'max_unit\']:     {\'maximum\': 2147483647, \'minimum\': 1, \'type\': \'integer\'}  On instance[\'inventories\'][\'MEM_ENCRYPTION_CONTEXT\'][\'max_unit\']:     0", "code": "placement.undefined_code", "request_id": "req-2206d054-b058-4f34-ac16-f6d4d04aab3f"}]}'

Based on my testing, I'm reasonably sure it's an issue with Python 3 vs. Python 2.  This is backed up by the observation that when I change `print_attachments()` in `subunit_trace.py` by commenting out the `utf8` encoding line, it fixes it:

            for line in detail.as_text().split('\n'):
                #line = line.encode('utf8')
                stream.write("    %s\n" % line)

However I suspect a more general solution across versions will need to use `six`.

### System information

**stestr version (`stestr --version`):** 2.3.1

**Python release (`python --version`):** 2.7.14 and 3.6.5

**Comment by mtreinish** [comment]
Yeah I'm assuming it's something with the python3 vs python2 story. This has been a constant thorn in the project, dating back to original fork where the differences between python 2 and 3 around character encoding and defaults makes things tricky to get right. This is also a likely source of the bug for failures when the attachments get too large. If you have any suggestions to make this work more cleanly I'd gladly apply them. 

I'm also just thinking out loud for a second. We could just prepare the stestr 3.0 branch (https://github.com/mtreinish/stestr/tree/remove-python2-support ) with whatever the appropriate behavior is for python3 and just have it ready for the early 2020 release. Then we don't have to try and have it working correctly in both py2 and py3 in all cases. Not sure that's a good fix though, since it'll leave users hanging for ~6 months.

**Comment by aspiers** [comment]
Thanks for looking at this.  I'm afraid my knowledge of character encoding etc. in Python 2 vs. 3 is pretty weak so I'm probably not going to be much use off the bat here, unless I can find some time to look into it deeper - but just coming back from vacation so will have a big backlog to deal with first :-(

**Comment by mtreinish** [comment]
Well that was easier to fix than I thought it would be, and it's my fault from 4 years ago too (well before I started stestr), see #272.
