### ISSUE TITLE
Switch windows testing to azure pipelines instead of appveyor

### ISSUE THREAD

**Issue by mtreinish** [mtreinish/stestr#249]
### Issue description

For work I recently switched projects away from using appveyor for windows testing to azure pipelines (https://github.com/marketplace/azure-pipelines ). It's a much more capable platform and the best part is the capacity available for open source projects is 10x that of appveyor. To make testing faster it would be good to look at switching our windows testing to use azure pipelines instead.

It might also be worth considering replacing our travis usage with azure pipelines too since it supports windows, osx, and linux and the 10 concurrent jobs exceeds the 3 we get from travis too.

**Comment by masayukig** [comment]
This was completed by #251 ? (partially?) We don't replace the all of the travis usage yet but windows testing was already switched.

**Comment by masayukig** [comment]
> It might also be worth considering replacing our travis usage with azure pipelines too since it supports windows, osx, and linux and the 10 concurrent jobs exceeds the 3 we get from travis too.

Oh, it supports OSX. That means we can have testing for the environment finally :)

**Comment by masayukig** [comment]
Can we close this issue?

**Comment by mtreinish** [comment]
Yeah, this is done for now. If we decide to migrate other things over to azure in the future we can do that or open a new issue for it.
