### ISSUE TITLE
New release time?

### ISSUE THREAD

**Issue by stephenfin** [mtreinish/stestr#284]
```
$ git tag --contains 4f65a4d318baf5b261ad9a35880c2da14fbbdff0
$
```

**Comment by stephenfin** [comment]
I don't know if that can be released as a 2.6.0 or if https://github.com/mtreinish/stestr/issues/237 means it'd have to be 3.0.0. It shouldn't matter for nova et al though give we're also dropping Python 2.7 at last \o/

**Comment by mtreinish** [comment]
I agree it's time to push a new release soon. I've been meaning to prep a 2.6.0 the past few weeks. I want to do a little manual testing locally and then I'll plan to push one up later today (or next week if I don't have time).

#237 is tracking a feature branch https://github.com/mtreinish/stestr/tree/remove-python2-support for 3.0.0 some point in 1H 2020.

**Comment by mtreinish** [comment]
I've just pushed up the 2.6.0 release: https://github.com/mtreinish/stestr/releases/tag/2.6.0 let me know if you have any issues with it

**Comment by mtreinish** [comment]
(the artifacts will be pushed to pypi after the travis job here: https://travis-ci.org/mtreinish/stestr/jobs/624748960?utm_medium=notification&utm_source=github_status finishes)

**Comment by stephenfin** [comment]
Awesome. Thanks, @mtreinish :smile:
