### ISSUE TITLE
How can I get the `TEST_ID`? Not find in the document.

### ISSUE THREAD

**Issue by hstk30** [mtreinish/stestr#286]
Hi, I want debug my test case with pdb, and I use the command `stestr run --pdb TEST_ID`, but how can I get the `TEST_ID`, I can't find the explanation in the document about `TEST_ID`. 
Is I missing something important?

**Comment by mtreinish** [comment]
TEST_ID there is just the python path to the module, class, and/or method to run. For example `project.tests.test_foo.TestFoo`. You can get the the list of test ids via the `stestr list` command. Additionally, the section just before it on the ` - -no-discover` flag has examples of TEST_ID that works exactly the same way: https://stestr.readthedocs.io/en/latest/MANUAL.html#running-tests

**Comment by hstk30** [comment]
Thanks for reply so quickly.  
Now, it works well for me. 
A good test tool!

**Comment by hstk30** [comment]
Hi, I find it not works everytime. 
Is it will cache something? 
Or have to do some prepare work before run test case ? 

I use `stestr run --pdb project.tests....` but not stop in my break point, just print the result. 
But after your first answer, it's successful for debugging.

**Comment by hstk30** [comment]
I find I can debug with pdb use option `--no-discover`, but `--pdb` is not work.
 I see the source code, the `--no-discover` is use `subprocess.Popen` to run the command `python3 -m stestr.subunit_runner.run TEST_ID`, and the `--pdb` is  delegated to the `<SubunitTestRunner>`, so  is the `SubunitTestRunner.run` not support the pdb debug or not set the parament??
