### ISSUE TITLE
Deprecate subunit2sql repository?

### ISSUE THREAD

**Issue by mtreinish** [mtreinish/stestr#307]
When we first started stestr the long term plan was to replace the file repository with a new repository built around subunit2sql which provides a much richer api. But in the years since then subunit2sql hasn't been super active and there are still some api gaps that prevent it from being a complete implementation. So we've had the sql repository type as an experimental optional repository backend. This is an undesirable state as we end up with a dual maintenance burden and any change to the interface we have to duplicate for both file and sql backends. We also have to maintain an optional requirements list and extra options for switching between repository types. At this point it seems unlikely that we'll ever end up finishing the sql repository backend, so I'm wondering if we should just call it and deprecate the backend for future removal.

**Comment by mtreinish** [comment]
@masayukig what do you think?

**Comment by masayukig** [comment]
> @masayukig what do you think?

yeah, I agree with you since we have enough bandwidth for that, unfortunately.
