### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by frenzymadness** [mtreinish/stestr#345]
Hello. Do you plan to release a new version? I'm interested in removed dependency on future because it's broken with the latest Python 3.12.

**Comment by mtreinish** [comment]
There is one PR I'd like to merge for 3.12 support: https://github.com/mtreinish/stestr/pull/344 once that merges I think we'll be ready to push a new release.

**Comment by frenzymadness** [comment]
I see, thank you.

**Comment by mtreinish** [comment]
4.1.0 was just released so I'm going to close this
