### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by masayukig** [mtreinish/stestr#40]
It would be good to support Windows to be happy Windows Python users. :)

**Comment by bclau** [comment]
Addressed by: https://github.com/mtreinish/stestr/pull/45

Not 100% functional yet, though. But as far stestr goes, the above PR seems suficient.

The only issue that remains is this: http://pastebin.com/2PhWzj6J

Files / FDs cannot be passed to select.select on Windows, but a minor change to subunit can address this, and it seems to be fine. Will link to the fix shortly.

**Comment by masayukig** [comment]
oh, subunit issue..

**Comment by bclau** [comment]
FYI, the subunit PR merged.

**Comment by mtreinish** [comment]
This is fixed now with: https://github.com/mtreinish/stestr/commit/2c2fc889b278b4154744b5e6a34710e405f72aad
