### ISSUE TITLE
No error handling for unknown arguments

### ISSUE THREAD

**Issue by mtreinish** [mtreinish/stestr#99]
Unknown args aren't being treated as fatal because we call parse_known_args() which makes it non-fatal. (https://docs.python.org/3.6/library/argparse.html#argparse.ArgumentParser.parse_known_args ) See: https://github.com/mtreinish/stestr/blob/master/stestr/cli.py#L94 

We use this method to get the regexes for selection, but this is really just a bug. The fix here is to just define a regexes param that has nargs='*' and switch the call to parse_args().

This was originally found by @masayukig in #98

**Comment by masayukig** [comment]
I made a pull request for using cliff #100 which resolving this issue. But if you want to resolve only this asap, I can take this.

**Comment by masayukig** [comment]
This can be closed with #100 merging.

**Comment by mtreinish** [comment]
Yep, let's close this:

$ stestr run --asd
usage: stestr run [-h] [--failing] [--serial] [--concurrency CONCURRENCY]
                  [--load-list LOAD_LIST] [--partial] [--subunit]
                  [--until-failure] [--analyze-isolation] [--isolated]
                  [--worker-file WORKER_PATH]
                  [--blacklist-file BLACKLIST_FILE]
                  [--whitelist-file WHITELIST_FILE]
                  [--black-regex BLACK_REGEX] [--no-discover TEST_ID]
                  [--random] [--combine] [--no-subunit-trace]
                  [--force-subunit-trace] [--color] [--slowest] [--abbreviate]
                  [filters [filters ...]]
stestr run: error: unrecognized arguments: --asd
